#!/usr/local/bin/python
"""This validates the source config for weblate. For a version it returns
the timestamp that was provided or 'none'"""

# Inspired by: https://github.com/cloudfoundry-community/slack-notification-resource
# to implement the concourse specs fully

import sys
import json

PAYLOAD = json.loads(sys.stdin.read())

try:
    URL = PAYLOAD["source"]["url"]
    KEY = PAYLOAD["source"]["key"]
    TRANSLATION = PAYLOAD["source"]["translation"]
except KeyError:
    print("Please provide a url, key and translation for weblate resource")
    sys.exit(1)

try:
    TIMESTAMP = PAYLOAD["version"]["timestamp"]
except TypeError:
    TIMESTAMP = "none"
except KeyError:
    TIMESTAMP = "none"


print(json.dumps([{"timestamp": TIMESTAMP}], sort_keys=True, indent=2))
